# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: foreman_param_lookup 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "foreman_param_lookup"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Riley Shott"]
  s.date = "2014-10-20"
  s.description = "Allows you to search for a record via fqdn, clientcert, or mac, and return its class parameter values"
  s.email = "rshott@sfu.ca"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/controllers/foreman_param_lookup/classifications_controller.rb",
    "config/routes.rb",
    "foreman_param_lookup.gemspec",
    "lib/foreman_param_lookup.rb",
    "lib/foreman_param_lookup/engine.rb"
  ]
  s.homepage = "https://github.com/sfu-rcg/foreman_param_lookup.git"
  s.licenses = ["GPL-3"]
  s.rubygems_version = "2.2.2"
  s.summary = "Allows you to search for a record via fqdn, clientcert, or mac, and return its class parameter values"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

